<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MyStartUpCompany.Worker-e3660f85-1e6f-4075-9d8b-cd245a0cb466</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyStartUpCompany.Persistence\MyStartUpCompany.Persistence.csproj" />
    <ProjectReference Include="..\MyStartUpCompany.Observability\MyStartUpCompany.Observability.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Handlers\AddCompany\Validators\" />
    <Folder Include="Processed\" />
  </ItemGroup>
</Project>
