// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyStartUpCompany.Persistence;

#nullable disable

namespace MyStartUpCompany.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516114329_SeededData")]
    partial class SeededData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyStartUpCompany.Persistence.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1234 Silicon Valley Blvd",
                            City = "San Francisco",
                            Country = "United States",
                            Description = "Leading AI and machine learning solutions provider",
                            Name = "TechVision Inc",
                            Phone = "+1-415-555-0101",
                            PostalCode = "94102",
                            Region = "CA"
                        },
                        new
                        {
                            Id = 2,
                            Address = "5678 Innovation Drive",
                            City = "San Jose",
                            Country = "United States",
                            Description = "Enterprise cloud infrastructure services",
                            Name = "CloudSync Solutions",
                            Phone = "+1-408-555-0102",
                            PostalCode = "95110",
                            Region = "CA"
                        },
                        new
                        {
                            Id = 3,
                            Address = "9012 Tech Park Way",
                            City = "Palo Alto",
                            Country = "United States",
                            Description = "Big data analytics and visualization platform",
                            Name = "DataFlow Analytics",
                            Phone = "+1-650-555-0103",
                            PostalCode = "94301",
                            Region = "CA"
                        },
                        new
                        {
                            Id = 4,
                            Address = "3456 Cyber Lane",
                            City = "San Diego",
                            Country = "United States",
                            Description = "Cybersecurity solutions for modern enterprises",
                            Name = "SecureNet Systems",
                            Phone = "+1-619-555-0104",
                            PostalCode = "92101",
                            Region = "CA"
                        },
                        new
                        {
                            Id = 5,
                            Address = "7890 Automation Street",
                            City = "Los Angeles",
                            Country = "United States",
                            Description = "CI/CD and DevOps automation specialists",
                            Name = "DevOps Masters",
                            Phone = "+1-213-555-0105",
                            PostalCode = "90001",
                            Region = "CA"
                        },
                        new
                        {
                            Id = 6,
                            Address = "2468 Research Boulevard",
                            City = "Mountain View",
                            Country = "United States",
                            Description = "Next-generation quantum computing research",
                            Name = "Quantum Computing Labs",
                            Phone = "+1-650-555-0106",
                            PostalCode = "94040",
                            Region = "CA"
                        },
                        new
                        {
                            Id = 7,
                            Address = "1357 App Street",
                            City = "Cupertino",
                            Country = "United States",
                            Description = "iOS and Android application development",
                            Name = "Mobile First Studios",
                            Phone = "+1-408-555-0107",
                            PostalCode = "95014",
                            Region = "CA"
                        },
                        new
                        {
                            Id = 8,
                            Address = "9753 Solar Avenue",
                            City = "Sacramento",
                            Country = "United States",
                            Description = "Renewable energy management systems",
                            Name = "Green Energy Tech",
                            Phone = "+1-916-555-0108",
                            PostalCode = "95814",
                            Region = "CA"
                        },
                        new
                        {
                            Id = 9,
                            Address = "4682 Medical Plaza",
                            City = "Irvine",
                            Country = "United States",
                            Description = "Medical device software and telemedicine",
                            Name = "HealthTech Innovations",
                            Phone = "+1-949-555-0109",
                            PostalCode = "92602",
                            Region = "CA"
                        },
                        new
                        {
                            Id = 10,
                            Address = "1111 Gaming Way",
                            City = "San Francisco",
                            Country = "United States",
                            Description = "Video game development and publishing",
                            Name = "GameDev Studios",
                            Phone = "+1-415-555-0110",
                            PostalCode = "94103",
                            Region = "CA"
                        },
                        new
                        {
                            Id = 11,
                            Address = "2222 Learning Lane",
                            City = "Oakland",
                            Country = "United States",
                            Description = "Educational technology and e-learning platforms",
                            Name = "EduTech Solutions",
                            Phone = "+1-510-555-0111",
                            PostalCode = "94612",
                            Region = "CA"
                        },
                        new
                        {
                            Id = 12,
                            Address = "3333 Crypto Court",
                            City = "Berkeley",
                            Country = "United States",
                            Description = "Cryptocurrency and blockchain development",
                            Name = "Blockchain Ventures",
                            Phone = "+1-510-555-0112",
                            PostalCode = "94704",
                            Region = "CA"
                        },
                        new
                        {
                            Id = 13,
                            Address = "4444 Vision Drive",
                            City = "Santa Clara",
                            Country = "United States",
                            Description = "Computer vision and image recognition",
                            Name = "AI Vision Systems",
                            Phone = "+1-408-555-0113",
                            PostalCode = "95050",
                            Region = "CA"
                        },
                        new
                        {
                            Id = 14,
                            Address = "5555 Aviation Road",
                            City = "Fremont",
                            Country = "United States",
                            Description = "Commercial drone software and services",
                            Name = "Drone Dynamics",
                            Phone = "+1-510-555-0114",
                            PostalCode = "94538",
                            Region = "CA"
                        },
                        new
                        {
                            Id = 15,
                            Address = "6666 Network Street",
                            City = "Menlo Park",
                            Country = "United States",
                            Description = "Social media analytics and management",
                            Name = "Social Connect Platform",
                            Phone = "+1-650-555-0115",
                            PostalCode = "94025",
                            Region = "CA"
                        },
                        new
                        {
                            Id = 16,
                            Address = "100 Wall Street",
                            City = "New York",
                            Country = "United States",
                            Description = "Financial technology and blockchain services",
                            Name = "FinTech Solutions LLC",
                            Phone = "+1-212-555-0201",
                            PostalCode = "10005",
                            Region = "NY"
                        },
                        new
                        {
                            Id = 17,
                            Address = "250 Broadway",
                            City = "New York",
                            Country = "United States",
                            Description = "Smart city data analytics platform",
                            Name = "Urban Analytics Corp",
                            Phone = "+1-212-555-0202",
                            PostalCode = "10007",
                            Region = "NY"
                        },
                        new
                        {
                            Id = 18,
                            Address = "42 Madison Avenue",
                            City = "New York",
                            Country = "United States",
                            Description = "Video streaming and content delivery network",
                            Name = "MediaStream Technologies",
                            Phone = "+1-212-555-0203",
                            PostalCode = "10010",
                            Region = "NY"
                        },
                        new
                        {
                            Id = 19,
                            Address = "150 Wall Street",
                            City = "New York",
                            Country = "United States",
                            Description = "Algorithmic trading and market analysis",
                            Name = "Trading Algorithms Inc",
                            Phone = "+1-212-555-0204",
                            PostalCode = "10005",
                            Region = "NY"
                        },
                        new
                        {
                            Id = 20,
                            Address = "333 Fifth Avenue",
                            City = "New York",
                            Country = "United States",
                            Description = "Performance marketing and ad tech",
                            Name = "Digital Marketing Hub",
                            Phone = "+1-212-555-0205",
                            PostalCode = "10016",
                            Region = "NY"
                        },
                        new
                        {
                            Id = 21,
                            Address = "444 Seventh Avenue",
                            City = "New York",
                            Country = "United States",
                            Description = "E-commerce and fashion technology",
                            Name = "Fashion Tech Lab",
                            Phone = "+1-212-555-0206",
                            PostalCode = "10018",
                            Region = "NY"
                        },
                        new
                        {
                            Id = 22,
                            Address = "555 Park Avenue",
                            City = "New York",
                            Country = "United States",
                            Description = "Property tech and real estate data",
                            Name = "Real Estate Analytics",
                            Phone = "+1-212-555-0207",
                            PostalCode = "10022",
                            Region = "NY"
                        },
                        new
                        {
                            Id = 23,
                            Address = "666 Lexington Avenue",
                            City = "New York",
                            Country = "United States",
                            Description = "Insurance technology solutions",
                            Name = "Insurance Tech Group",
                            Phone = "+1-212-555-0208",
                            PostalCode = "10022",
                            Region = "NY"
                        },
                        new
                        {
                            Id = 24,
                            Address = "777 Third Avenue",
                            City = "New York",
                            Country = "United States",
                            Description = "Legal practice management software",
                            Name = "Legal Tech Partners",
                            Phone = "+1-212-555-0209",
                            PostalCode = "10017",
                            Region = "NY"
                        },
                        new
                        {
                            Id = 25,
                            Address = "100 MetroTech Center",
                            City = "Brooklyn",
                            Country = "United States",
                            Description = "Custom software development agency",
                            Name = "Brooklyn Software Collective",
                            Phone = "+1-718-555-0210",
                            PostalCode = "11201",
                            Region = "NY"
                        },
                        new
                        {
                            Id = 26,
                            Address = "200 Main Street",
                            City = "Buffalo",
                            Country = "United States",
                            Description = "Manufacturing automation software",
                            Name = "Buffalo Tech Innovations",
                            Phone = "+1-716-555-0211",
                            PostalCode = "14202",
                            Region = "NY"
                        },
                        new
                        {
                            Id = 27,
                            Address = "300 East Avenue",
                            City = "Rochester",
                            Country = "United States",
                            Description = "Enterprise data management solutions",
                            Name = "Rochester Data Systems",
                            Phone = "+1-585-555-0212",
                            PostalCode = "14604",
                            Region = "NY"
                        },
                        new
                        {
                            Id = 28,
                            Address = "1500 Energy Plaza",
                            City = "Houston",
                            Country = "United States",
                            Description = "Smart grid and renewable energy solutions",
                            Name = "Energy Grid Innovations",
                            Phone = "+1-713-555-0301",
                            PostalCode = "77002",
                            Region = "TX"
                        },
                        new
                        {
                            Id = 29,
                            Address = "600 Congress Avenue",
                            City = "Austin",
                            Country = "United States",
                            Description = "Custom software development and consulting",
                            Name = "Austin Code Labs",
                            Phone = "+1-512-555-0302",
                            PostalCode = "78701",
                            Region = "TX"
                        },
                        new
                        {
                            Id = 30,
                            Address = "2000 Ross Avenue",
                            City = "Dallas",
                            Country = "United States",
                            Description = "Enterprise software solutions provider",
                            Name = "Lone Star Tech",
                            Phone = "+1-214-555-0303",
                            PostalCode = "75201",
                            Region = "TX"
                        },
                        new
                        {
                            Id = 31,
                            Address = "1600 Louisiana Street",
                            City = "Houston",
                            Country = "United States",
                            Description = "Energy sector data analytics",
                            Name = "Oil & Gas Analytics",
                            Phone = "+1-713-555-0304",
                            PostalCode = "77002",
                            Region = "TX"
                        },
                        new
                        {
                            Id = 32,
                            Address = "700 Red River Street",
                            City = "Austin",
                            Country = "United States",
                            Description = "Event management and ticketing software",
                            Name = "Live Music Tech",
                            Phone = "+1-512-555-0305",
                            PostalCode = "78701",
                            Region = "TX"
                        },
                        new
                        {
                            Id = 33,
                            Address = "2100 Pearl Street",
                            City = "Dallas",
                            Country = "United States",
                            Description = "Telecom infrastructure and 5G technology",
                            Name = "Telecommunications Solutions",
                            Phone = "+1-214-555-0306",
                            PostalCode = "75201",
                            Region = "TX"
                        },
                        new
                        {
                            Id = 34,
                            Address = "800 Dolorosa Street",
                            City = "San Antonio",
                            Country = "United States",
                            Description = "Military-grade security systems",
                            Name = "San Antonio Cybersecurity",
                            Phone = "+1-210-555-0307",
                            PostalCode = "78205",
                            Region = "TX"
                        },
                        new
                        {
                            Id = 35,
                            Address = "900 Commerce Street",
                            City = "Fort Worth",
                            Country = "United States",
                            Description = "Supply chain management software",
                            Name = "Fort Worth Logistics Tech",
                            Phone = "+1-817-555-0308",
                            PostalCode = "76102",
                            Region = "TX"
                        },
                        new
                        {
                            Id = 36,
                            Address = "1000 Space Center Boulevard",
                            City = "Houston",
                            Country = "United States",
                            Description = "Aerospace software and satellite systems",
                            Name = "Space Tech Ventures",
                            Phone = "+1-281-555-0309",
                            PostalCode = "77058",
                            Region = "TX"
                        },
                        new
                        {
                            Id = 37,
                            Address = "1100 South Lamar",
                            City = "Austin",
                            Country = "United States",
                            Description = "Mobile and console game development",
                            Name = "Austin Gaming Studios",
                            Phone = "+1-512-555-0310",
                            PostalCode = "78704",
                            Region = "TX"
                        },
                        new
                        {
                            Id = 38,
                            Address = "1201 Third Avenue",
                            City = "Seattle",
                            Country = "United States",
                            Description = "Multi-cloud management platform",
                            Name = "Pacific Cloud Services",
                            Phone = "+1-206-555-0401",
                            PostalCode = "98101",
                            Region = "WA"
                        },
                        new
                        {
                            Id = 39,
                            Address = "500 Pike Street",
                            City = "Seattle",
                            Country = "United States",
                            Description = "Healthcare IT solutions",
                            Name = "Emerald Software Group",
                            Phone = "+1-206-555-0402",
                            PostalCode = "98101",
                            Region = "WA"
                        },
                        new
                        {
                            Id = 40,
                            Address = "410 Terry Avenue North",
                            City = "Seattle",
                            Country = "United States",
                            Description = "Online marketplace technology",
                            Name = "E-Commerce Platform Inc",
                            Phone = "+1-206-555-0403",
                            PostalCode = "98109",
                            Region = "WA"
                        },
                        new
                        {
                            Id = 41,
                            Address = "2401 Utah Avenue South",
                            City = "Seattle",
                            Country = "United States",
                            Description = "Restaurant and cafe POS systems",
                            Name = "Coffee Tech Solutions",
                            Phone = "+1-206-555-0404",
                            PostalCode = "98134",
                            Region = "WA"
                        },
                        new
                        {
                            Id = 42,
                            Address = "100 North Riverside Avenue",
                            City = "Renton",
                            Country = "United States",
                            Description = "Flight simulation and training software",
                            Name = "Aerospace Simulation Systems",
                            Phone = "+1-425-555-0405",
                            PostalCode = "98057",
                            Region = "WA"
                        },
                        new
                        {
                            Id = 43,
                            Address = "1000 Denny Way",
                            City = "Seattle",
                            Country = "United States",
                            Description = "Colocation and edge computing",
                            Name = "Northwest Data Center",
                            Phone = "+1-206-555-0406",
                            PostalCode = "98109",
                            Region = "WA"
                        },
                        new
                        {
                            Id = 44,
                            Address = "808 West Spokane Falls Boulevard",
                            City = "Spokane",
                            Country = "United States",
                            Description = "Custom enterprise applications",
                            Name = "Spokane Software Works",
                            Phone = "+1-509-555-0407",
                            PostalCode = "99201",
                            Region = "WA"
                        },
                        new
                        {
                            Id = 45,
                            Address = "1950 Pacific Avenue",
                            City = "Tacoma",
                            Country = "United States",
                            Description = "Industrial Internet of Things solutions",
                            Name = "Tacoma Industrial IoT",
                            Phone = "+1-253-555-0408",
                            PostalCode = "98402",
                            Region = "WA"
                        },
                        new
                        {
                            Id = 46,
                            Address = "75 State Street",
                            City = "Boston",
                            Country = "United States",
                            Description = "Biotechnology research and development",
                            Name = "BioTech Innovations",
                            Phone = "+1-617-555-0501",
                            PostalCode = "02109",
                            Region = "MA"
                        },
                        new
                        {
                            Id = 47,
                            Address = "1 Memorial Drive",
                            City = "Cambridge",
                            Country = "United States",
                            Description = "Artificial intelligence research lab",
                            Name = "Cambridge AI Research",
                            Phone = "+1-617-555-0502",
                            PostalCode = "02142",
                            Region = "MA"
                        },
                        new
                        {
                            Id = 48,
                            Address = "200 Berkeley Street",
                            City = "Boston",
                            Country = "United States",
                            Description = "Medical device software and diagnostics",
                            Name = "MedTech Solutions",
                            Phone = "+1-617-555-0503",
                            PostalCode = "02116",
                            Region = "MA"
                        },
                        new
                        {
                            Id = 49,
                            Address = "77 Massachusetts Avenue",
                            City = "Cambridge",
                            Country = "United States",
                            Description = "Autonomous robotics systems",
                            Name = "Robotics Engineering Lab",
                            Phone = "+1-617-555-0504",
                            PostalCode = "02139",
                            Region = "MA"
                        },
                        new
                        {
                            Id = 50,
                            Address = "300 The Fenway",
                            City = "Boston",
                            Country = "United States",
                            Description = "Digital textbooks and learning platforms",
                            Name = "EdTech Publishing",
                            Phone = "+1-617-555-0505",
                            PostalCode = "02115",
                            Region = "MA"
                        },
                        new
                        {
                            Id = 51,
                            Address = "100 Front Street",
                            City = "Worcester",
                            Country = "United States",
                            Description = "Technology incubator and coworking",
                            Name = "Worcester Innovation Hub",
                            Phone = "+1-508-555-0506",
                            PostalCode = "01608",
                            Region = "MA"
                        },
                        new
                        {
                            Id = 52,
                            Address = "500 Boylston Street",
                            City = "Boston",
                            Country = "United States",
                            Description = "Quantum encryption technology",
                            Name = "Quantum Security Systems",
                            Phone = "+1-617-555-0507",
                            PostalCode = "02116",
                            Region = "MA"
                        },
                        new
                        {
                            Id = 53,
                            Address = "233 South Wacker Drive",
                            City = "Chicago",
                            Country = "United States",
                            Description = "Enterprise resource planning systems",
                            Name = "WindyCity Solutions",
                            Phone = "+1-312-555-0601",
                            PostalCode = "60606",
                            Region = "IL"
                        },
                        new
                        {
                            Id = 54,
                            Address = "444 West Lake Street",
                            City = "Chicago",
                            Country = "United States",
                            Description = "Colocation and managed hosting services",
                            Name = "Midwest Data Center",
                            Phone = "+1-312-555-0602",
                            PostalCode = "60661",
                            Region = "IL"
                        },
                        new
                        {
                            Id = 55,
                            Address = "141 West Jackson Boulevard",
                            City = "Chicago",
                            Country = "United States",
                            Description = "Commodities trading software",
                            Name = "Trading Platform Technologies",
                            Phone = "+1-312-555-0603",
                            PostalCode = "60604",
                            Region = "IL"
                        },
                        new
                        {
                            Id = 56,
                            Address = "225 North Michigan Avenue",
                            City = "Chicago",
                            Country = "United States",
                            Description = "Rail and freight optimization",
                            Name = "Transportation Logistics AI",
                            Phone = "+1-312-555-0604",
                            PostalCode = "60601",
                            Region = "IL"
                        },
                        new
                        {
                            Id = 57,
                            Address = "100 West Monroe Street",
                            City = "Chicago",
                            Country = "United States",
                            Description = "Restaurant management systems",
                            Name = "Food Service Tech",
                            Phone = "+1-312-555-0605",
                            PostalCode = "60603",
                            Region = "IL"
                        },
                        new
                        {
                            Id = 58,
                            Address = "1 North Dearborn Street",
                            City = "Chicago",
                            Country = "United States",
                            Description = "Industrial process optimization",
                            Name = "Manufacturing Analytics Pro",
                            Phone = "+1-312-555-0606",
                            PostalCode = "60602",
                            Region = "IL"
                        },
                        new
                        {
                            Id = 59,
                            Address = "1000 Brickell Avenue",
                            City = "Miami",
                            Country = "United States",
                            Description = "Mobile app development studio",
                            Name = "Sunshine Software",
                            Phone = "+1-305-555-0701",
                            PostalCode = "33131",
                            Region = "FL"
                        },
                        new
                        {
                            Id = 60,
                            Address = "100 West Livingston Street",
                            City = "Orlando",
                            Country = "United States",
                            Description = "Technology incubator and coworking space",
                            Name = "Orlando Tech Hub",
                            Phone = "+1-407-555-0702",
                            PostalCode = "32801",
                            Region = "FL"
                        },
                        new
                        {
                            Id = 61,
                            Address = "1000 Universal Studios Plaza",
                            City = "Orlando",
                            Country = "United States",
                            Description = "Attraction management and ticketing",
                            Name = "Theme Park Systems",
                            Phone = "+1-407-555-0703",
                            PostalCode = "32819",
                            Region = "FL"
                        },
                        new
                        {
                            Id = 62,
                            Address = "2000 Biscayne Boulevard",
                            City = "Miami",
                            Country = "United States",
                            Description = "Maritime navigation and booking systems",
                            Name = "Cruise Line Technologies",
                            Phone = "+1-305-555-0704",
                            PostalCode = "33137",
                            Region = "FL"
                        },
                        new
                        {
                            Id = 63,
                            Address = "3000 Bayshore Boulevard",
                            City = "Tampa",
                            Country = "United States",
                            Description = "Healthcare management platforms",
                            Name = "Tampa Bay HealthTech",
                            Phone = "+1-813-555-0705",
                            PostalCode = "33629",
                            Region = "FL"
                        },
                        new
                        {
                            Id = 64,
                            Address = "4000 NASA Parkway",
                            City = "Cape Canaveral",
                            Country = "United States",
                            Description = "Aerospace engineering software",
                            Name = "Space Coast Engineering",
                            Phone = "+1-321-555-0706",
                            PostalCode = "32920",
                            Region = "FL"
                        },
                        new
                        {
                            Id = 65,
                            Address = "1700 Lincoln Street",
                            City = "Denver",
                            Country = "United States",
                            Description = "Cloud infrastructure and SaaS",
                            Name = "Mile High Software",
                            Phone = "+1-303-555-0801",
                            PostalCode = "80203",
                            Region = "CO"
                        },
                        new
                        {
                            Id = 66,
                            Address = "191 Peachtree Street",
                            City = "Atlanta",
                            Country = "United States",
                            Description = "Payment processing solutions",
                            Name = "Atlanta FinTech Group",
                            Phone = "+1-404-555-0802",
                            PostalCode = "30303",
                            Region = "GA"
                        },
                        new
                        {
                            Id = 67,
                            Address = "100 West Washington Street",
                            City = "Phoenix",
                            Country = "United States",
                            Description = "Enterprise data warehousing",
                            Name = "Phoenix Data Solutions",
                            Phone = "+1-602-555-0803",
                            PostalCode = "85003",
                            Region = "AZ"
                        },
                        new
                        {
                            Id = 68,
                            Address = "1000 Southwest Broadway",
                            City = "Portland",
                            Country = "United States",
                            Description = "Open source software development",
                            Name = "Portland Open Source",
                            Phone = "+1-503-555-0804",
                            PostalCode = "97205",
                            Region = "OR"
                        },
                        new
                        {
                            Id = 69,
                            Address = "1 Woodward Avenue",
                            City = "Detroit",
                            Country = "United States",
                            Description = "Automotive software and IoT",
                            Name = "Detroit Auto Tech",
                            Phone = "+1-313-555-0805",
                            PostalCode = "48226",
                            Region = "MI"
                        },
                        new
                        {
                            Id = 70,
                            Address = "1234 Market Street",
                            City = "Philadelphia",
                            Country = "United States",
                            Description = "Electronic health records systems",
                            Name = "Philadelphia HealthCare IT",
                            Phone = "+1-215-555-0806",
                            PostalCode = "19107",
                            Region = "PA"
                        },
                        new
                        {
                            Id = 71,
                            Address = "3799 Las Vegas Boulevard",
                            City = "Las Vegas",
                            Country = "United States",
                            Description = "Casino and gaming software",
                            Name = "Las Vegas Gaming Tech",
                            Phone = "+1-702-555-0807",
                            PostalCode = "89109",
                            Region = "NV"
                        },
                        new
                        {
                            Id = 72,
                            Address = "150 Fourth Avenue North",
                            City = "Nashville",
                            Country = "United States",
                            Description = "Music production and streaming tech",
                            Name = "Nashville Music Software",
                            Phone = "+1-615-555-0808",
                            PostalCode = "37219",
                            Region = "TN"
                        },
                        new
                        {
                            Id = 73,
                            Address = "50 East South Temple",
                            City = "Salt Lake City",
                            Country = "United States",
                            Description = "Outdoor recreation and fitness apps",
                            Name = "Salt Lake Outdoor Tech",
                            Phone = "+1-801-555-0809",
                            PostalCode = "84111",
                            Region = "UT"
                        },
                        new
                        {
                            Id = 74,
                            Address = "100 North Tryon Street",
                            City = "Charlotte",
                            Country = "United States",
                            Description = "Core banking software",
                            Name = "Charlotte Banking Systems",
                            Phone = "+1-704-555-0810",
                            PostalCode = "28202",
                            Region = "NC"
                        },
                        new
                        {
                            Id = 75,
                            Address = "50 South Sixth Street",
                            City = "Minneapolis",
                            Country = "United States",
                            Description = "Agricultural technology and farm management",
                            Name = "Minneapolis AgriTech",
                            Phone = "+1-612-555-0811",
                            PostalCode = "55402",
                            Region = "MN"
                        },
                        new
                        {
                            Id = 76,
                            Address = "1100 Main Street",
                            City = "Kansas City",
                            Country = "United States",
                            Description = "Warehouse automation and robotics",
                            Name = "Kansas City Logistics AI",
                            Phone = "+1-816-555-0812",
                            PostalCode = "64105",
                            Region = "MO"
                        },
                        new
                        {
                            Id = 77,
                            Address = "10 Downing Street",
                            City = "London",
                            Country = "United Kingdom",
                            Description = "Digital marketing and web development",
                            Name = "London Digital Agency",
                            Phone = "+44-20-7946-0901",
                            PostalCode = "SW1A 2AA",
                            Region = "England"
                        },
                        new
                        {
                            Id = 78,
                            Address = "100 King Street West",
                            City = "Toronto",
                            Country = "Canada",
                            Description = "Software consulting and training",
                            Name = "Toronto Tech Collective",
                            Phone = "+1-416-555-0902",
                            PostalCode = "M5X 1A9",
                            Region = "ON"
                        },
                        new
                        {
                            Id = 79,
                            Address = "1 Macquarie Place",
                            City = "Sydney",
                            Country = "Australia",
                            Description = "Cloud migration specialists",
                            Name = "Sydney Cloud Partners",
                            Phone = "+61-2-9555-0903",
                            PostalCode = "2000",
                            Region = "NSW"
                        },
                        new
                        {
                            Id = 80,
                            Address = "Unter den Linden 77",
                            City = "Berlin",
                            Country = "Germany",
                            Description = "IoT and embedded systems development",
                            Name = "Berlin Innovation Labs",
                            Phone = "+49-30-2555-0904",
                            PostalCode = "10117",
                            Region = "BE"
                        },
                        new
                        {
                            Id = 81,
                            Address = "1 Marina Boulevard",
                            City = "Singapore",
                            Country = "Singapore",
                            Description = "Financial services technology platform",
                            Name = "Singapore FinTech Hub",
                            Phone = "+65-6555-0905",
                            PostalCode = "018989"
                        },
                        new
                        {
                            Id = 82,
                            Address = "1-1-1 Shibuya",
                            City = "Tokyo",
                            Country = "Japan",
                            Description = "Industrial automation and robotics",
                            Name = "Tokyo Robotics Corp",
                            Phone = "+81-3-5555-0906",
                            PostalCode = "150-0002"
                        },
                        new
                        {
                            Id = 83,
                            Address = "10 Avenue des Champs-Élysées",
                            City = "Paris",
                            Country = "France",
                            Description = "Luxury fashion e-commerce platform",
                            Name = "Paris Fashion Tech",
                            Phone = "+33-1-4555-0907",
                            PostalCode = "75008",
                            Region = "IDF"
                        },
                        new
                        {
                            Id = 84,
                            Address = "Science Park 904",
                            City = "Amsterdam",
                            Country = "Netherlands",
                            Description = "Machine learning and data analytics",
                            Name = "Amsterdam Data Science",
                            Phone = "+31-20-5555-0908",
                            PostalCode = "1098 XH",
                            Region = "NH"
                        },
                        new
                        {
                            Id = 85,
                            Address = "70 Sir John Rogerson's Quay",
                            City = "Dublin",
                            Country = "Ireland",
                            Description = "European cloud infrastructure provider",
                            Name = "Dublin Cloud Services",
                            Phone = "+353-1-555-0909",
                            PostalCode = "D02 R296",
                            Region = "D"
                        },
                        new
                        {
                            Id = 86,
                            Address = "Sveavägen 46",
                            City = "Stockholm",
                            Country = "Sweden",
                            Description = "Sustainable technology solutions",
                            Name = "Stockholm GreenTech",
                            Phone = "+46-8-555-0910",
                            PostalCode = "111 34",
                            Region = "AB"
                        },
                        new
                        {
                            Id = 87,
                            Address = "MG Road 100",
                            City = "Bangalore",
                            Country = "India",
                            Description = "Offshore development and IT services",
                            Name = "Bangalore Software Solutions",
                            Phone = "+91-80-5555-0911",
                            PostalCode = "560001",
                            Region = "KA"
                        },
                        new
                        {
                            Id = 88,
                            Address = "Avenida Paulista 1000",
                            City = "São Paulo",
                            Country = "Brazil",
                            Description = "Latin American e-commerce platform",
                            Name = "São Paulo Digital",
                            Phone = "+55-11-5555-0912",
                            PostalCode = "01310-100",
                            Region = "SP"
                        },
                        new
                        {
                            Id = 89,
                            Address = "1055 West Hastings Street",
                            City = "Vancouver",
                            Country = "Canada",
                            Description = "Cross-platform mobile application development",
                            Name = "Vancouver Mobile Apps",
                            Phone = "+1-604-555-1001",
                            PostalCode = "V6E 2E9",
                            Region = "BC"
                        },
                        new
                        {
                            Id = 90,
                            Address = "120 Collins Street",
                            City = "Melbourne",
                            Country = "Australia",
                            Description = "Business intelligence and analytics platform",
                            Name = "Melbourne Analytics Hub",
                            Phone = "+61-3-9555-1002",
                            PostalCode = "3000",
                            Region = "VIC"
                        },
                        new
                        {
                            Id = 91,
                            Address = "Bahnhofstrasse 50",
                            City = "Zurich",
                            Country = "Switzerland",
                            Description = "Enterprise security and compliance software",
                            Name = "Zurich SecureTech",
                            Phone = "+41-44-555-1003",
                            PostalCode = "8001",
                            Region = "ZH"
                        },
                        new
                        {
                            Id = 92,
                            Address = "123 Gangnam-daero",
                            City = "Seoul",
                            Country = "South Korea",
                            Description = "Mobile and PC game development",
                            Name = "Seoul Game Studios",
                            Phone = "+82-2-555-1004",
                            PostalCode = "06236"
                        },
                        new
                        {
                            Id = 93,
                            Address = "1 International Finance Centre",
                            City = "Hong Kong",
                            Country = "Hong Kong",
                            Description = "Financial services technology solutions",
                            Name = "Hong Kong FinServe",
                            Phone = "+852-2555-1005",
                            PostalCode = "999077"
                        },
                        new
                        {
                            Id = 94,
                            Address = "Passeig de Gràcia 85",
                            City = "Barcelona",
                            Country = "Spain",
                            Description = "Urban technology and IoT solutions",
                            Name = "Barcelona Smart City",
                            Phone = "+34-93-555-1006",
                            PostalCode = "08008",
                            Region = "CAT"
                        },
                        new
                        {
                            Id = 95,
                            Address = "Vesterbrogade 6A",
                            City = "Copenhagen",
                            Country = "Denmark",
                            Description = "Sustainable technology and clean energy software",
                            Name = "Copenhagen Green Solutions",
                            Phone = "+45-33-555-1007",
                            PostalCode = "1620"
                        },
                        new
                        {
                            Id = 96,
                            Address = "Rothschild Boulevard 100",
                            City = "Tel Aviv",
                            Country = "Israel",
                            Description = "Cybersecurity and AI research",
                            Name = "Tel Aviv Innovation Labs",
                            Phone = "+972-3-555-1008",
                            PostalCode = "6688101"
                        },
                        new
                        {
                            Id = 97,
                            Address = "Sheikh Zayed Road",
                            City = "Dubai",
                            Country = "United Arab Emirates",
                            Description = "Enterprise digital transformation services",
                            Name = "Dubai Tech Hub",
                            Phone = "+971-4-555-1009",
                            PostalCode = "00000"
                        },
                        new
                        {
                            Id = 98,
                            Address = "Stephansplatz 1",
                            City = "Vienna",
                            Country = "Austria",
                            Description = "Data analytics and business intelligence",
                            Name = "Vienna Data Systems",
                            Phone = "+43-1-555-1010",
                            PostalCode = "1010",
                            Region = "W"
                        },
                        new
                        {
                            Id = 99,
                            Address = "Karl Johans gate 10",
                            City = "Oslo",
                            Country = "Norway",
                            Description = "Marine navigation and shipping software",
                            Name = "Oslo Maritime Tech",
                            Phone = "+47-22-555-1011",
                            PostalCode = "0154"
                        },
                        new
                        {
                            Id = 100,
                            Address = "Rue de la Loi 200",
                            City = "Brussels",
                            Country = "Belgium",
                            Description = "Government and regulatory compliance software",
                            Name = "Brussels EU Tech",
                            Phone = "+32-2-555-1012",
                            PostalCode = "1049",
                            Region = "BRU"
                        });
                });

            modelBuilder.Entity("MyStartUpCompany.Persistence.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
