apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: mystartupcorp
type: Opaque
stringData:
  connection-string: "Server=sqlserver.database.windows.net,1433;Initial Catalog=MyStartUpCompanyDb;User Id=sqladmin;Password=CHANGE_ME;Encrypt=true;Connection Timeout=30;"
---
apiVersion: v1
kind: Secret
metadata:
  name: servicebus-secrets
  namespace: mystartupcorp
type: Opaque
stringData:
  connection-string: "Endpoint=sb://mystartupcorp.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: acr-secrets
  namespace: mystartupcorp
type: kubernetes.io/dockercfg
data:
  .dockercfg: LS1DT05URVhUIEZPUiBET0NLRVIJ
---
apiVersion: v1
kind: Secret
metadata:
  name: applicationinsights-secrets
  namespace: observability
type: Opaque
stringData:
  connection-string: "InstrumentationKey=CHANGE_ME;IngestionEndpoint=https://eastus-1.in.applicationinsights.azure.com/"
